name: vdevice-main-workflow

permissions:
  contents: read

on:
  push:
    branches: [ main, develop, 'sprint/**', 'release/**', 'test/**' ]
  pull_request:
    branches: [ main, develop, 'sprint/**', 'release/**', 'test/**' ]

jobs:
  trigger-vdevice-qemu-setup:
    uses: ./.github/workflows/vdevice-docker-pull.yml
